globals:
  cluster_nodes:
    - 172.31.17.24:1000
    - 172.31.18.160:1000
    - 172.31.17.250:1000

raw_record_topic:
  test_run_01_raw

staging_topic:
  test_run_01_staging


user_topics:
  - alias: scratch_topic
    name: t1

